### ISSUE TITLE
Increment method

### ISSUE THREAD

**Issue by FallingSnow** [mmomtchev/SharedMap#4]
Is a get followed by a set an atomically safe function? Or do you need to take an exclusive lock?
I'm trying to increment the value.
```js
const totalRequests = this.sharedmap.get("metrics.requests.total") || 0;
this.sharedmap.set("metrics.requests.total", parseInt(totalRequests) + 1);
```

**Comment by mmomtchev** [comment]
Both get and set are atomic as individual functions. But if you want to be sure that no other thread will change the value between the get and the set, you need an exclusive lock.

**Comment by FallingSnow** [comment]
Got it. Thank you!
