### ISSUE TITLE
How can I get SharedMap's length

### ISSUE THREAD

**Issue by xxyjskx1987** [mmomtchev/SharedMap#8]
How can I get SharedMap's length?
I want to know how much the space is used.

**Comment by xxyjskx1987** [comment]
this is helpful to monitor memory's change.

**Comment by xxyjskx1987** [comment]
anothor question 31 * 1024 * 1024 is the max,not 2^32,why?

**Comment by mmomtchev** [comment]
The memory used is constant, all memory is statically-allocated at creation
You can get the number of elements in the Map by calling length()
I don't understand the second question, what is limited to 2^32? If you mean the number of entries, SharedMap won't be able to handle 4 billion entries, no matter what
And JS arrays are limited 2^32 - 1 entries

**Comment by xxyjskx1987** [comment]
May be 2^32 I read the wrong document.
So,I use length function and calculate memory by myself.
